/**
 * Pre-built demo guide. Pressing "Try demo trip" jumps straight to the
 * day-by-day guide with no planning wait — useful for demos and reviews.
 */
import { demoTripInput, type ItineraryItem, type TripResult } from "@/lib/waypoint/types";

const item = (
  timeOfDay: ItineraryItem["timeOfDay"],
  title: string,
  description: string,
  durationMinutes: number,
  estimatedCost: number,
  whyItFits: string,
  imageQuery: string,
  accessibilityNote?: string,
): ItineraryItem => ({
  timeOfDay,
  title,
  description,
  durationMinutes,
  estimatedCost,
  whyItFits,
  imageQuery,
  ...(accessibilityNote ? { accessibilityNote } : {}),
});

export const demoTripResult: TripResult = {
  input: demoTripInput,
  generatedAt: "2026-01-01T09:00:00.000Z",
  brief: {
    constraints: [
      "About 20 minutes of walking at a time, with frequent seated breaks",
      "Late starts — nothing booked before 10am",
      "Total budget of $2,500 for two travellers over six days",
    ],
    priorities: [
      { label: "Food", weight: 5, note: "Markets and neighbourhood kitchens over famous restaurants" },
      { label: "Culture", weight: 4, note: "Shrines, gardens and craft districts" },
      { label: "Photography", weight: 3, note: "Golden-hour viewpoints reachable by train" },
    ],
    budgetStrategy: "Mid-range hotel near a JR line, most meals in local restaurants, trains over taxis.",
    accessibilityConstraints: ["Short walking legs", "Elevator-served stations where possible", "Seated dining"],
    paceGuidance: "Two anchor stops a day plus one relaxed evening plan.",
    risks: ["Weekend crowds at Senso-ji", "Rain days in early summer"],
  },
  plan: {
    title: "",
    destination: "Tokyo, Japan",
    destinationRationale:
      "Tokyo pairs world-class food with short, elevator-served train hops, so a low-walking itinerary still reaches everything.",
    overview:
      "Six unhurried days built around neighbourhood food, quiet gardens and golden-hour views, all within a few train stops of your hotel.",
    currency: "USD",
    budget: {
      accommodation: 900,
      food: 720,
      transportation: 180,
      activities: 380,
      miscellaneous: 200,
      total: 2380,
      notes: "Leaves roughly $120 spare for souvenirs or one splurge dinner.",
    },
    highlights: [
      { title: "Tsukiji Outer Market breakfast", reason: "Best food-to-walking ratio in the city." },
      { title: "Shinjuku Gyoen gardens", reason: "Benches every few minutes and almost no crowds midweek." },
      { title: "Sunset from Shibuya Sky", reason: "Seated viewing deck with the city's best skyline light." },
    ],
    practicalNotes: [
      "Load a Suica card on arrival — it works on every train and most convenience stores.",
      "Most stations you'll use have elevators; look for the green accessibility signs.",
      "Restaurants seat small groups quickly before 6pm.",
    ],
    days: [
      {
        day: 1,
        theme: "Easing into the city",
        estimatedDayCost: 165,
        activityLevel: "Relaxed",
        items: [
          item(
            "morning",
            "Settle in at Hotel Niwa Tokyo",
            "A calm garden hotel by **Suidobashi Station**, two stops from almost everything on this trip.",
            60,
            0,
            "Central, quiet and elevator-served, so days start without a long walk.",
            "Hotel Niwa Tokyo garden Tokyo",
            "Step-free entrance and lifts to all floors.",
          ),
          item(
            "afternoon",
            "Koishikawa Korakuen Garden",
            "A 17th-century strolling garden with flat gravel paths, ponds and benches at every turn.",
            90,
            5,
            "Gentle first outing with seating throughout.",
            "Koishikawa Korakuen garden pond Tokyo",
            "Flat paths; a few small bridges can be skipped.",
          ),
          item(
            "evening",
            "Yakitori dinner at Torikizoku Kanda",
            "Grilled skewers and cold beer at a friendly counter — everything is seated and quick.",
            90,
            45,
            "Low-key local dinner that suits a late start and an early night.",
            "yakitori grilled skewers restaurant Tokyo",
          ),
        ],
      },
      {
        day: 2,
        theme: "Market breakfast and old Tokyo",
        estimatedDayCost: 190,
        activityLevel: "Moderate",
        items: [
          item(
            "morning",
            "Tsukiji Outer Market tasting walk",
            "Tamagoyaki, grilled scallops and knife shops packed into a few covered lanes.",
            120,
            40,
            "Maximum food variety inside a very small footprint.",
            "Tsukiji Outer Market food stalls Tokyo",
            "Narrow lanes; go before 10am when it is calmer.",
          ),
          item(
            "afternoon",
            "Senso-ji Temple and Nakamise",
            "Tokyo's oldest temple, approached through a lantern-lit shopping street.",
            100,
            0,
            "Headline culture stop with a step-free side entrance.",
            "Senso-ji temple lanterns Asakusa Tokyo",
            "Ramp access on the temple's west side.",
          ),
          item(
            "evening",
            "Sumida River cruise to Hinode",
            "A seated 40-minute boat ride past bridges and the **Tokyo Skytree** at dusk.",
            60,
            22,
            "Sightseeing without any walking at all.",
            "Sumida River cruise boat Tokyo",
          ),
        ],
      },
      {
        day: 3,
        theme: "Gardens and coffee",
        estimatedDayCost: 150,
        activityLevel: "Relaxed",
        items: [
          item(
            "morning",
            "Shinjuku Gyoen National Garden",
            "Wide lawns, a greenhouse and a teahouse; benches roughly every hundred metres.",
            120,
            4,
            "Quiet, flat and easy to shorten if you're tired.",
            "Shinjuku Gyoen national garden lawn Tokyo",
            "Fully paved main loop, accessible toilets near each gate.",
          ),
          item(
            "afternoon",
            "Kissa coffee break at Cafe de L'ambre",
            "A 1948 coffee house in **Ginza** where aged beans are brewed cup by cup.",
            60,
            18,
            "A seated break that still feels like sightseeing.",
            "vintage Japanese kissaten coffee shop Tokyo",
          ),
          item(
            "evening",
            "Omoide Yokocho small plates",
            "A lane of six-seat kitchens serving grilled fish, noodles and pickles.",
            90,
            50,
            "Neighbourhood dining rather than a tourist restaurant.",
            "Omoide Yokocho alley izakaya Shinjuku Tokyo",
          ),
        ],
      },
      {
        day: 4,
        theme: "Crafts and skyline light",
        estimatedDayCost: 210,
        activityLevel: "Moderate",
        items: [
          item(
            "morning",
            "Kappabashi kitchenware street",
            "Blocks of knife makers, ceramics and hand-carved cooking tools.",
            90,
            30,
            "Food-lover shopping in a flat, uncrowded street.",
            "Kappabashi kitchenware knife shop Tokyo",
          ),
          item(
            "afternoon",
            "Nezu Museum garden",
            "Asian art indoors and a mossy hillside garden with a covered tea pavilion.",
            100,
            15,
            "Calm culture stop with plenty of seating.",
            "Nezu Museum garden tea house Tokyo",
            "Lift to all galleries; garden has some gentle slopes.",
          ),
          item(
            "evening",
            "Sunset at Shibuya Sky",
            "An open-air rooftop deck 230m up, with loungers facing **Mount Fuji** on clear evenings.",
            90,
            40,
            "The trip's best photography window, reached entirely by lift.",
            "Shibuya Sky rooftop observation deck sunset Tokyo",
            "Lifts and escalators the whole way; seating on the deck.",
          ),
        ],
      },
      {
        day: 5,
        theme: "A slow day out of the centre",
        estimatedDayCost: 175,
        activityLevel: "Relaxed",
        items: [
          item(
            "morning",
            "Yanaka Ginza shopping lane",
            "An old-Tokyo street of croquette stands, cats and small galleries.",
            100,
            18,
            "Quiet, flat and full of snacks — the opposite of a crowded landmark.",
            "Yanaka Ginza shopping street Tokyo",
          ),
          item(
            "afternoon",
            "Soba lunch at Kanda Matsuya",
            "Hand-cut buckwheat noodles in a century-old wooden dining room.",
            75,
            35,
            "Seated regional specialty close to your hotel.",
            "handmade soba noodles restaurant Tokyo",
          ),
          item(
            "evening",
            "Onsen soak at Thermae-yu",
            "Natural hot-spring baths and relaxation loungers in **Shinjuku**.",
            120,
            30,
            "Recovery evening before the last full day.",
            "Japanese onsen hot spring bath Tokyo",
            "Attendant-assisted entry and seated shower stations.",
          ),
        ],
      },
      {
        day: 6,
        theme: "Last tastes and views",
        estimatedDayCost: 200,
        activityLevel: "Moderate",
        items: [
          item(
            "morning",
            "Sushi breakfast at Sushi Dai Toyosu",
            "Chef's selection at the counter inside **Toyosu Market**.",
            90,
            60,
            "One splurge meal, seated and short.",
            "sushi counter chef nigiri Toyosu Tokyo",
          ),
          item(
            "afternoon",
            "teamLab Planets digital art",
            "Barefoot rooms of water, mirrors and projected flowers in **Toyosu**.",
            100,
            32,
            "Photography-first stop that is one stop from breakfast.",
            "teamLab Planets digital art installation Tokyo",
            "Staff assistance available; some water rooms can be skipped.",
          ),
          item(
            "evening",
            "Farewell tempura at Tenmatsu Shibuya",
            "Course tempura fried in front of you at a nine-seat counter.",
            105,
            70,
            "Quiet final dinner with no walking after dark.",
            "tempura counter restaurant chef Tokyo",
          ),
        ],
      },
    ],
  },
  check: {
    fitScore: 92,
    summary: "Comfortably within budget, low-walking throughout, and food-led as requested.",
    pros: [
      "Every day starts late and keeps walking legs under 20 minutes",
      "Six food experiences across markets, counters and neighbourhood kitchens",
      "Total lands about $120 under your $2,500 budget",
      "Two golden-hour photography stops with seating",
    ],
    cons: [
      "Senso-ji is busy on weekends — go early if your dates land on one",
      "Shibuya Sky is outdoors and closes the deck in heavy rain",
    ],
    checks: [
      { name: "Budget", status: "pass", detail: "$2,380 of $2,500 allocated." },
      { name: "Walking load", status: "pass", detail: "No leg longer than 20 minutes." },
      { name: "Pace", status: "pass", detail: "Two anchor stops plus one evening plan per day." },
      { name: "Crowds", status: "warn", detail: "Asakusa and Shibuya peak on weekends." },
    ],
    issues: [],
  },
};
